name: digit_ui_components
description: Digit UI Design specification
version: 0.0.2-dev.5
homepage: https://github.com/egovernments/DIGIT-UI-LIBRARIES/tree/master/flutter/digit-ui-components

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.5
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.0
  horizontal_data_table: ^4.1.3
  location: ^6.0.2
  location_platform_interface: ^4.0.0
  json_annotation: ^4.7.0
  logging: ^1.1.0
  build_runner: ^2.2.1
  reactive_forms: ^17.0.0
  plugin_platform_interface: ^2.1.3
  fluttertoast: ^8.1.2
  flutter_spinkit: ^5.1.0
  overlay_builder: ^1.1.0
  intl: ^0.19.0
  geolocator: ^10.1.0
  collection: ^1.15.0
  flutter_styled_toast: ^2.2.1
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  file_picker: ^8.0.0+1
  flutter_dropzone: ^3.0.7
  image_picker: ^1.0.8
  dotted_border: ^2.1.0
  camera: ^0.11.0+1
  path_provider: ^2.0.11
  visibility_detector: ^0.4.0+2
  lottie: ^3.1.0
  universal_html: ^2.2.4
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.3
  json_serializable: ^6.4.0
  bloc_test: ^9.1.0
  mockito: ^5.0.15
  build_runner: ^2.1.0
  freezed: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/svg/
    - assets/animated_json/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
    - family: Roboto Condensed
      fonts:
        - asset: assets/fonts/Roboto/RobotoCondensed-Regular.ttf

  uses-material-design: true

