# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "develop",  "master" ]
  pull_request:
    branches: [ "develop",  "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3
       - uses: dart-lang/setup-dart@v1

       - name: Flutter action
         uses: subosito/flutter-action@v2.8.0
         with:
          flutter-version: "3.10.5"
          
       - name: Disable Config
         run: flutter --disable-telemetry 
         
       - name: Navigate to Root Folder
         run: cd flutter/digit-ui-components/example

       - name: PWD
         run: ls


       - name: Install Dependencies
         run: flutter pub get
         

         

       - name: Run Tests
         run: flutter test
